# standard jekyll configuration options

exclude: ['Rakefile', 'README.md', 'config.rb']

# configuration required for some pages

domain: blog.example.com
title: My Blog Title
author: Me
email: me@example.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
